import {
    Briefcase,
    Users,
    BrainCircuit,
    Monitor,
    ShieldCheck,
    Workflow,
    PhoneCall,
    PlugZap,
    KeyRound,
    Settings,
    Cloud,
    Server,
    Landmark,
    FolderKanban,
    Headset,
    Phone,
    Wrench,
    BarChart3,
    Database,
    FileText,
    MonitorSmartphone,
    Building2,
    UserRoundSearch,
    CircleHelp,
} from "lucide-react";

const iconMap = {
    "IT Strategy & Consulting": Briefcase,
    "Sales & CRM": Users,
    "AI Readiness & Copilot Enablement": BrainCircuit,
    "Modern Workplace": Monitor,
    "Cybersecurity, Identity & Compliance": ShieldCheck,
    "Business Process Automation": Workflow,
    "Teams Calling & Business Voice": PhoneCall,
    "Enterprise System Integration": PlugZap,
    "Microsoft Licensing & Optimization": KeyRound,
    "Managed IT": Settings,
    "Organizational Change Management": Users,
    "Cloud Infrastructure": Cloud,
    "Data Center Hosting": Server,
    "Finance": Landmark,
    "Project Operations": FolderKanban,
    "Customer Service": Headset,
    "Contact Center": Phone,
    "Field Service": Wrench,
    "Customer Insights": BarChart3,
    "Enterprise Resource Platform": Database,
    "Intranet Portals & Document Management": FileText,
    "Business Intelligence & Reporting": BarChart3,
    "Endpoint & Device Management": MonitorSmartphone,
    "Enterprise Modernization": BarChart3,
    "IT Staffing": UserRoundSearch,
};

export const getServiceIcon = (label) => {
    return iconMap[label] || CircleHelp;
};